---
# Program/Department Title
title: Africology and African American Studies
# Subdirectory (with / at only at beginning)
baseurl: /africology-and-african-american-studies

# Program Information
# Short tagline for tweets (<100 characters)
tagline: This is our life's work
# Longer descriptions for link previews (<250 characters)
description: 'The Department of Africology and African American Studies presents students with an ongoing synthesis of the best research and scholarship on historical, cultural, scientific and economic issues confronting African and African American people.'
# List of related keywords for search engines
keywords: highered, college, university, philadelphia, Temple

# Address
address:
  room: 8th Floor, Room 811
  building: Gladfelter Hall
  street: 1115 Polett Walk
  city: Philadelphia, PA 19122
  email: liberal-arts-africology-african-american-studies@temple.edu
  phone: 215-204-8491

# Social Media
# Put in only the username unless otherwise noted
# If social media does not apply to your department, keep it blank or use the default values.
social:
  # Facebook - http://www.facebook.com/AFAMatTU
  # if your page does not have a custom URL, create one!
  facebook: TempleLiberalArts
  # Twitter - https://twitter.com/TULiberalArts/
  twitter: TULiberalArts
  # Instagram - https://www.instagram.com/tuliberalarts/
  instagram: TULiberalArts
  # Snapchat - USERNAME
  snapchat:
  # GitHub - https://github.com/USERNAME or https://github.com/USERNAME/REPO
  github:
  # DeviantArt - http://USERNAME.deviantart.com/
  deviantart:
  # Vimeo - https://vimeo.com/USERNAME
  vimeo:
  # YouTube - Paste the FULL URL below
  youtube:
  # LinkedIn - Paste the FULL URL below
  linkedin:
  # Slack - Paste the FULL URL below
  slack:

# University & College Information
university: 
  name: Temple University
  url: https://temple.edu/
college:
  name: College of Liberal Arts
  url: https://liberalarts.temple.edu/

# Google Tag Manager OR Google Analytics
google_analytics: 


google_tag_manager: GTM-58ZL5B

# CSV/JSON/YAML data feeds URLs, to be fetched before each build
events-feed: https://liberalarts.temple.edu/events/africology-and-african-american-studies/csv
news-feed: https://liberalarts.temple.edu/news/africology-and-african-american-studies/csv
faculty-feed: https://liberalarts.temple.edu/profiles/africology-and-african-american-studies/csv

# Development Config
# If you do not have access to 'tutheme', use 'minima' instead.
theme: tutheme

# Global Site Config
# DO NOT edit below unless if you know what you're doing!
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
timezone: UTC
collections:
  pages:
    title: Pages
    output: true
    layout: page
permalink: /:title

# Prose
prose:
  rooturl: pages
  media: media
  ignore:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
  - index.html
  - _config.yml
  metadata:
    pages:
      - name: title
        field:
          element: text
          label: Title
      - name: permalink
        field:
          element: text
          label: Permalink
      - name: layout
        field:
          element: select
          label: Page layout
          options:
            - name: page
              value: page
            - name: faculty
              value: faculty
            - name: faculty2
              value: faculty2
            - name: home
              value: home

# Jekyll Ignore
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
  - s3_website.yml
  - .sass-cache
  - .travis.yml
  - .ruby-version
  - .gitignore
  - vendor
  - _site
  - node_modules
  - docker-compose.yml
